// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB08LPTvF7dbPOMa1BglBCdQvtdU894pr4',
    appId: '1:1016289559471:web:680995095406f73b0ae55a',
    messagingSenderId: '1016289559471',
    projectId: 'online-quran-learning-8e069',
    authDomain: 'online-quran-learning-8e069.firebaseapp.com',
    storageBucket: 'online-quran-learning-8e069.appspot.com',
    measurementId: 'G-S2X3EB8719',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WywHeZC_vTA7e1BmC5yrUyHsq6g8GW0',
    appId: '1:1016289559471:android:05e7a58933ec8ced0ae55a',
    messagingSenderId: '1016289559471',
    projectId: 'online-quran-learning-8e069',
    storageBucket: 'online-quran-learning-8e069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuRHoaMlr3Q6nSi-wii4icgrv1ijrCGgU',
    appId: '1:1016289559471:ios:aefd1e1af03d94260ae55a',
    messagingSenderId: '1016289559471',
    projectId: 'online-quran-learning-8e069',
    storageBucket: 'online-quran-learning-8e069.appspot.com',
    iosClientId: '1016289559471-379fn09sejo0cosbirodp4ndp0g7m0cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineQuranLearning',
  );
}
